/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SmeNewListingRouteImport } from './routes/sme.new-listing'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ListingsRouteImport } from './routes/listings'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CvBuilderRouteImport } from './routes/cv-builder'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ListingsIdRouteImport } from './routes/listings.$id'
import { Route as LearnIdRouteImport } from './routes/learn.$id'

const SmeNewListingRoute = SmeNewListingRouteImport.update({
  id: '/sme/new-listing',
  path: '/sme/new-listing',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsRoute = ListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CvBuilderRoute = CvBuilderRouteImport.update({
  id: '/cv-builder',
  path: '/cv-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsIdRoute = ListingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ListingsRoute,
} as any)
const LearnIdRoute = LearnIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LearnRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/cv-builder': typeof CvBuilderRoute
  '/dashboard': typeof DashboardRoute
  '/learn': typeof LearnRouteWithChildren
  '/listings': typeof ListingsRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sme/new-listing': typeof SmeNewListingRoute
  '/learn/$id': typeof LearnIdRoute
  '/listings/$id': typeof ListingsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/cv-builder': typeof CvBuilderRoute
  '/dashboard': typeof DashboardRoute
  '/learn': typeof LearnRouteWithChildren
  '/listings': typeof ListingsRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sme/new-listing': typeof SmeNewListingRoute
  '/learn/$id': typeof LearnIdRoute
  '/listings/$id': typeof ListingsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/cv-builder': typeof CvBuilderRoute
  '/dashboard': typeof DashboardRoute
  '/learn': typeof LearnRouteWithChildren
  '/listings': typeof ListingsRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sme/new-listing': typeof SmeNewListingRoute
  '/learn/$id': typeof LearnIdRoute
  '/listings/$id': typeof ListingsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications'
    | '/cv-builder'
    | '/dashboard'
    | '/learn'
    | '/listings'
    | '/login'
    | '/register'
    | '/sme/new-listing'
    | '/learn/$id'
    | '/listings/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applications'
    | '/cv-builder'
    | '/dashboard'
    | '/learn'
    | '/listings'
    | '/login'
    | '/register'
    | '/sme/new-listing'
    | '/learn/$id'
    | '/listings/$id'
  id:
    | '__root__'
    | '/'
    | '/applications'
    | '/cv-builder'
    | '/dashboard'
    | '/learn'
    | '/listings'
    | '/login'
    | '/register'
    | '/sme/new-listing'
    | '/learn/$id'
    | '/listings/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicationsRoute: typeof ApplicationsRoute
  CvBuilderRoute: typeof CvBuilderRoute
  DashboardRoute: typeof DashboardRoute
  LearnRoute: typeof LearnRouteWithChildren
  ListingsRoute: typeof ListingsRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SmeNewListingRoute: typeof SmeNewListingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sme/new-listing': {
      id: '/sme/new-listing'
      path: '/sme/new-listing'
      fullPath: '/sme/new-listing'
      preLoaderRoute: typeof SmeNewListingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings': {
      id: '/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof ListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv-builder': {
      id: '/cv-builder'
      path: '/cv-builder'
      fullPath: '/cv-builder'
      preLoaderRoute: typeof CvBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/$id': {
      id: '/listings/$id'
      path: '/$id'
      fullPath: '/listings/$id'
      preLoaderRoute: typeof ListingsIdRouteImport
      parentRoute: typeof ListingsRoute
    }
    '/learn/$id': {
      id: '/learn/$id'
      path: '/$id'
      fullPath: '/learn/$id'
      preLoaderRoute: typeof LearnIdRouteImport
      parentRoute: typeof LearnRoute
    }
  }
}

interface ListingsRouteChildren {
  ListingsIdRoute: typeof ListingsIdRoute
}

const ListingsRouteChildren: ListingsRouteChildren = {
  ListingsIdRoute: ListingsIdRoute,
}

const ListingsRouteWithChildren = ListingsRoute._addFileChildren(
  ListingsRouteChildren,
)

interface LearnRouteChildren {
  LearnIdRoute: typeof LearnIdRoute
}

const LearnRouteChildren: LearnRouteChildren = {
  LearnIdRoute: LearnIdRoute,
}

const LearnRouteWithChildren = LearnRoute._addFileChildren(LearnRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicationsRoute: ApplicationsRoute,
  CvBuilderRoute: CvBuilderRoute,
  DashboardRoute: DashboardRoute,
  LearnRoute: LearnRouteWithChildren,
  ListingsRoute: ListingsRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SmeNewListingRoute: SmeNewListingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
